require_relative 'hello'
require_relative 'player'
require_relative 'status'
require_relative 'ocntopic'
require_relative 'team'
require_relative 'announce'
require_relative 'bracket'
require_relative 'ip'
